<?php
return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2'                                 => true,
        'array_syntax'                          => ['syntax' => 'short'],
        'combine_consecutive_unsets'            => true,
        'heredoc_to_nowdoc'                     => true,
        'linebreak_after_opening_tag'           => true,
        'lowercase_cast'                        => true,
        'lowercase_constants'                   => true,
        'mb_str_functions'                      => true,
        'method_separation'                     => true,
        'modernize_types_casting'               => true,
        'native_function_casing'                => true,
        'new_with_braces'                       => true,
        'no_blank_lines_after_class_opening'    => true,
        'no_blank_lines_after_phpdoc'           => true,
        'no_empty_comment'                      => true,
        'no_empty_phpdoc'                       => true,
        'no_empty_statement'                    => true,
        'no_extra_consecutive_blank_lines'      => [
            'break',
            'continue',
            'extra',
            'return',
            'throw',
            'use',
            'parenthesis_brace_block',
            'square_brace_block',
            'curly_brace_block',
        ],
        'no_leading_namespace_whitespace'       => true,
        'no_php4_constructor'                   => true,
        'no_short_echo_tag'                     => true,
        'no_unreachable_default_argument_value' => true,
        'no_useless_else'                       => true,
        'no_useless_return'                     => true,
        'ordered_class_elements'                => [
            'use_trait',
            'constant_public',
            'constant_protected',
            'constant_private',
            'property_public',
            'property_protected',
            'property_private',
            'construct',
            'destruct',
            'magic',
            'phpunit',
            'method_public',
            'method_protected',
            'method_private',
        ],
        'ordered_imports'                       => [
            'sortAlgorithm' => 'alpha',
        ],
        'php_unit_strict'                       => true,
        'php_unit_construct'                    => true,
        'php_unit_dedicate_assert'              => true,
        'phpdoc_no_empty_return'                => true,
        'phpdoc_no_package'                     => true,
        'phpdoc_scalar'                         => true,
        'phpdoc_types'                          => true,
        'pow_to_exponentiation'                 => true,
        'random_api_migration'                  => true,
        'return_type_declaration'               => [
            'space_before' => 'none',
        ],
        'semicolon_after_instruction'           => true,
        'short_scalar_cast'                     => true,
        'single_quote'                          => true,
        'space_after_semicolon'                 => true,
        'standardize_not_equals'                => true,
        'strict_comparison'                     => true,
        'strict_param'                          => true,
        'ternary_to_null_coalescing'            => true,
        'trailing_comma_in_multiline_array'     => true,
        'declare_strict_types'                  => true,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()->in(__DIR__ . '/src')
    );
