language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --prefer-dist

script: bin/phpspec run --format=pretty --no-code-generation
